version: "3"
services:
  server1:
    build: service-1
    ports:
      - "8001:8001"
    restart: always
    command: npm start 
  server2:
    build: service-2
    restart: always  
    volumes:
      - ./service-2:/usr/src/app    
    command: npm start  
  